Сумма ЗП
js-tasks-ru/jsbasic-20210809_payk1-93 pull request #6
Opened 2021-08-14 12:32 UTC by KatnikovAA

Сделал сложение всех ЗП 
и проверку на их наличие в объекте

2021-08-14 12:33 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-08-16 04:12 UTC, koalex requested changes
Исправить решение

2021-08-16 04:12 UTC, koalex commented on 2-module/1-task/index.js
> +  if("John" in salaries && "Pete" in salaries && "Ann" in salaries ) {
Решение подогнано под тесты. Нужно сделать универсальное решение.
```
function sumSalary(salaries) {
  let sumOfSalaries = 0;

  for (let key in salaries) {
    let isSalary = typeof salaries[key] === 'number';

    if (isSalary) {
      sumOfSalaries += salaries[key];
    }
  }

  return sumOfSalaries;
}
```

2021-08-16 12:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2021-08-17 07:59 UTC, koalex approved these changes

2021-08-17 07:59 UTC, merged